import torch
import torch.optim as optim
import os
import matplotlib.pyplot as plt
from .model import VectorField
from .flow import ConditionalFlowMatching
from .solver import ODESolver

class MoleculeFlowTrainer:
    def __init__(self, molecule_data, hidden_dim=64, lr=1e-3, device='cpu'):
        self.device = device
        self.molecule_data = molecule_data.to(device)
        self.dim = molecule_data.x.shape[1]
        
        # Initialize model with atom type support
        self.net = VectorField(in_dim=self.dim, 
                               hidden_dim=hidden_dim, 
                               out_dim=self.dim, 
                               use_atom_types=True).to(device)
                               
        self.flow = ConditionalFlowMatching(sigma=0.0) 
        self.optimizer = optim.Adam(self.net.parameters(), lr=lr)
        
    def train_step(self):
        self.net.train()
        self.optimizer.zero_grad()
        
        # Single molecule overfitting for now
        x1 = self.molecule_data.x.unsqueeze(0) 
        adj = self.molecule_data.adj.unsqueeze(0)
        atom_types = self.molecule_data.atom_types.unsqueeze(0)
        
        x0 = torch.randn_like(x1)
        
        # Pass atom_types to compute_loss -> net
        loss = self.flow.compute_loss(self.net, x1, x0, adj, atom_types=atom_types)
        
        loss.backward()
        self.optimizer.step()
        
        return loss.item()

    def train(self, n_steps=1000, log_interval=100, save_dir='results/molecule'):
        os.makedirs(save_dir, exist_ok=True)
        
        print(f"Starting molecule training on {self.device}...")
        for step in range(n_steps):
            loss = self.train_step()
            
            if (step + 1) % log_interval == 0:
                print(f"Step {step+1}: Loss = {loss:.6f}")
                
        torch.save(self.net.state_dict(), f"{save_dir}/model.pt")
        print("Training complete.")

    def sample_and_save(self, save_dir='results/molecule'):
        self.net.eval()
        solver = ODESolver(self.net, method='rk4')
        
        x0 = torch.randn(1, self.molecule_data.num_nodes, self.dim).to(self.device)
        adj = self.molecule_data.adj.unsqueeze(0).to(self.device)
        atom_types = self.molecule_data.atom_types.unsqueeze(0).to(self.device)
        
        # Pass atom_types to solver
        x_final, trajectory = solver.solve(x0, adj, atom_types=atom_types)
        
        # Save trajectory as XYZ file for visualization in molecular viewers (VMD, PyMOL, etc.)
        self.save_xyz_trajectory(trajectory, self.molecule_data.atom_types, f"{save_dir}/trajectory.xyz")
        
        # Also plot final frame 2D projection or 3D scatter
        self.plot_3d_snapshot(x_final[0], self.molecule_data.atom_types, f"{save_dir}/final_conformer.png")
        print(f"Results saved to {save_dir}")

    def save_xyz_trajectory(self, trajectory, atom_types, filepath):
        """
        Saves trajectory to XYZ format.
        """
        # Mapping from atomic num to symbol (simplified)
        pt = {1: 'H', 6: 'C', 7: 'N', 8: 'O', 9: 'F', 15: 'P', 16: 'S', 17: 'Cl'}
        
        with open(filepath, 'w') as f:
            for x in trajectory:
                x = x[0].detach().cpu().numpy()
                n_atoms = x.shape[0]
                f.write(f"{n_atoms}\n")
                f.write("Generated by Graph Flow Matching\n")
                for i in range(n_atoms):
                    atom_num = atom_types[i].item()
                    symbol = pt.get(atom_num, 'X')
                    f.write(f"{symbol} {x[i, 0]:.6f} {x[i, 1]:.6f} {x[i, 2]:.6f}\n")

    def plot_3d_snapshot(self, x, atom_types, save_path):
        x = x.detach().cpu().numpy()
        atom_types = atom_types.detach().cpu().numpy()
        
        fig = plt.figure()
        ax = fig.add_subplot(111, projection='3d')
        
        colors = {1: 'gray', 6: 'black', 7: 'blue', 8: 'red', 9: 'green'}
        c = [colors.get(a, 'magenta') for a in atom_types]
        
        ax.scatter(x[:, 0], x[:, 1], x[:, 2], c=c, s=100)
        
        # Draw bonds? Need adjacency. 
        # For now just atoms.
        
        plt.savefig(save_path)
        plt.close()
